### ISSUE TITLE
Failed to Install the APK 

### ISSUE THREAD

**Issue by Msyu1020** [nnperfwins/nnPerf#2]
Hello I'm trying to install the apk nnPerf_v1.0.apk on my device, but it failed. I wonder the reason why it doesn't work.

1. **adb**
![nnPerf](https://github.com/nnperfwins/nnPerf/assets/99970874/bbe4448a-c12b-4419-a3fe-1cfaefbc3b92)

2. **download the apk on device and install directly**
![nnPerf2](https://github.com/nnperfwins/nnPerf/assets/99970874/067ddaae-fdd0-4a2e-9d2e-ea68829e72f3)

**Running Environments:**
- Xiaomi Pad 6 Pro     Android 13
- HUAWEI Nova 7      HarmonyOS 4.0.0

**Comment by nnperfwins** [comment]
Thank you for your attention and feedback. 

1. After carefully reviewing the device environment information you provided, we conducted a thorough test of nnPerf on a HUAWEI P40 operating under HarmonyOS. During our testing, we did not encounter the issue you've described.

**Running Environments:**
![device env](https://github.com/nnperfwins/nnPerf/assets/147254180/311cb93a-68ee-4f6c-9fd8-a7416eeb8d82)

2. Based on the error message you provided, it appears there might have been **an incomplete download** of our nnPerf_v1.0.apk, **which should be 265MB rather than 128KB.** This discrepancy could potentially be attributed to Large File Storage (LFS) issues.

To ensure optimal functionality, we suggest you **verify the integrity of the nnPerf_v1.0.apk** file or consider cloning our project directly from the repository. We appreciate your continued engagement and look forward to assisting you further.

**Comment by Msyu1020** [comment]
Thanks for your help! I've confirmed that the reason is just the incomplete download. And when I use `git clone`, nnPerf runs on my HUAWEI device  successfully.

However, it goes wrong on Xiaomi Pad. Maybe the full text is helpful:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
	at com.example.android.nnPerf.Camera2BasicFragment.updateActiveModel(Camera2BasicFragment.java:341)
	at com.example.android.nnPerf.Camera2BasicFragment.access$700(Camera2BasicFragment.java:74)
	at com.example.android.nnPerf.Camera2BasicFragment$5.onItemClick(Camera2BasicFragment.java:497)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1222)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3236)
	at android.widget.AbsListView$3.run(AbsListView.java:4240)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8401)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by nnperfwins** [comment]
Thank you for reaching out and sharing the details of the issue you are experiencing. 

Based on your feedback, we have identified that the issue arises from compatibility concerns with certain commands in the official TFLITE DNN demo program used by nnPerf on specific versions of **Android 13**. 

This issue is **not directly related to the nnPerf tool itself**. We are actively addressing this issue and plan to release an update soon, including new features for nnPerf. In the meantime, you may consider the following alternatives:

1. Use a device **running on Android 12 or an earlier version.**
2. Plug nnPerf into your own DNN inference project.

We appreciate your understanding and patience as we work to resolve this matter.
